// import type { Metadata } from "next";

import "./login.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex">
      <div className="flex-1">{children}</div>
      <section className="login-sidebar w-xl bg-cover"></section>
    </div>
  );
}
